name: Scheduled Playwright Tests Admin

on: 
  workflow_dispatch:
#  schedule:
#    - cron: '0 0 * * *' # Scheduled to run at 00:00 UTC

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Run Docker
        run: docker compose up -d

      - name: Install Dependencies
        run: npm ci
        
      - name: Install Playwright Browsers
        run: npm install @playwright/test && npx playwright install --with-deps
        
      # Run all in directory
      # - name: Run Playwright tests
      #   run: npx playwright test tests/admin/landingPage
      
      # Run only one
      # - name: Run Playwright tests
      #   run: npx playwright test tests/admin/landingPage/visibility.spec.js
      
      # Run all tests using 4 workers
      - name: Run Playwright tests
        run: npx playwright test tests/admin --workers=2
      
      # Upload Playwright HTML Report
      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      # Upload Playwright Test Artifacts (Videos, Traces, Screenshots)
      # - name: Upload Playwright Artifacts
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: playwright-artifacts
      #     path: tests-results/
      #     retention-days: 30
